name: Stream Recorder Action

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: 'رابط البث m3u8'
        required: true
      duration:
        description: 'مدة التسجيل بالثواني'
        default: '300'

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run Recorder Script
        env:
          M3U8_URL: ${{ github.event.inputs.m3u8_url }}
          DURATION: ${{ github.event.inputs.duration }}
        run: python main.py
